package Vista;

import Model.Articulo;
import Model.Cliente;
import Decorator.Paquete;
import java.util.Iterator;
import javax.swing.JOptionPane;
/**
 * @author Gabriel Islas
 * @author Victor Lavalle
 * @auhtor Eberth Mezeta
 */
public class CarritoV extends javax.swing.JFrame {
    
    Cliente cliente;
    CentroComercialV centro;

    public CarritoV(CentroComercialV centro,Cliente cliente) {
        this.centro = centro;
        this.cliente=cliente;
        
       initComponents();
        this.setLocationRelativeTo(null);
        llenarArticulos();
        LlenarPaquetes();
        this.TituloLBL.setText("Carrito de:"+ this.cliente.getNombre());
        calcularmonto();
        
    }

    
     public void llenarArticulos() {
        String tabla[][] = new String[this.cliente.getCarrito().sizeArt()][4];
        Iterator articulosIterator = this.cliente.getCarrito().getArticulos();
        int i = 0;
        while (articulosIterator.hasNext()) {
            Articulo articulo = (Articulo) articulosIterator.next();
            tabla[i][0] = articulo.getNombre();
            tabla[i][1] = articulo.getID();
            tabla[i][2] = articulo.getIDT();
            tabla[i][3] = "$" + String.format("%.2f", articulo.getPrecio());
            i++;
        }

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Articulo","ID","Tienda", "Precio"}
        ));
    }
       
       
         public void LlenarPaquetes() {
       String tabla[][] = new String[this.cliente.getCarrito().sizePaq()][3];
        Iterator paquetesIterator = this.cliente.getCarrito().getPaq();
        int i = 0;
        while (paquetesIterator.hasNext()) {
            Paquete paquete = (Paquete) paquetesIterator.next();
            tabla[i][0] = paquete.getNombre();
            tabla[i][1] = "$" + String.format("%.2f", paquete.getPrecio());
            i++;
        }

        TablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Paquete", "Precio"}
        ));
    }

    
    public void calcularmonto(){
    int monto=0;
      Iterator i = this.cliente.getCarrito().getArticulos();
      Iterator j = this.cliente.getCarrito().getPaq();
      
      while(i.hasNext()){
      
          Articulo art= (Articulo) i.next();
          
          monto+=art.getPrecio();
      
      }
      
      while (j.hasNext()){
      
          Paquete paq = (Paquete) j.next();
      
          monto+=paq.getPrecio();
      
      }
     
      this.Monto.setText(" $"+monto);
      
    
    }
    
    
    /**
     * Creates new form Carrito
     */
    public CarritoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLBL = new javax.swing.JLabel();
        PagarBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Monto = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloLBL.setText("Carrito de:XXX ");
        jPanel1.add(TituloLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 210, 30));

        PagarBTN.setBackground(new java.awt.Color(3, 218, 198));
        PagarBTN.setText("Pagar");
        PagarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(PagarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 180, 40));

        jLabel2.setText("Lista de  Paquetes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 20));

        jLabel3.setText("Lista de  Articulos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jButton3.setText("Eliminar Paquete  del Carrito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jButton4.setText("Eliminar Articulo del Carrito");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setText("Total a Pagar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        Monto.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Monto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 100, 30));

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 40));

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaArticulos.setAutoscrolls(false);
        jScrollPane3.setViewportView(TablaArticulos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 220));

        TablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPaquetes.setAutoscrolls(false);
        jScrollPane4.setViewportView(TablaPaquetes);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 370, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int index= this.TablaPaquetes.getSelectedRow();
       
        if(index!=-1){
        int counter=0;
        Iterator i = this.cliente.getCarrito().getPaq();
        
        while(i.hasNext()&&  counter<= index){
        
            Paquete paq= (Paquete) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().QuitarPaquete(paq);
            }
            counter++;
        
        }
        
       LlenarPaquetes();
        calcularmonto();
        
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        
        
        this.dispose();
        centro.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void PagarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBTNActionPerformed
        
        
         this.cliente.setCarrito(null);
         
        JOptionPane.showMessageDialog(null,"El cliente " + this.cliente.getNombre() + " ha realizado la compra con exito");
        
        this.dispose();
        centro.setVisible(true);
        
    }//GEN-LAST:event_PagarBTNActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          int index= this.TablaArticulos.getSelectedRow();
       
        if(index!=-1){
        int counter=0;
        Iterator i = this.cliente.getCarrito().getArticulos();
        
        while(i.hasNext()&&  counter<= index){
        
            Articulo art= (Articulo) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().Quitar(art);
            }
            counter++;
        
        }
        
        llenarArticulos();
        calcularmonto();
        
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Monto;
    private javax.swing.JButton PagarBTN;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTable TablaPaquetes;
    private javax.swing.JLabel TituloLBL;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
