package Vista;

import Model.Tienda;
import Decorator.Paquete;
import Model.Articulo;
import Model.Cliente;
import java.util.Iterator;
import javax.swing.JOptionPane;
/**
 * @author Gabriel Islas
 * @author Victor Lavalle
 * @author Eberth Mezeta
 */
public class TiendaV extends javax.swing.JFrame {
    
   private  CentroComercialV centro;
   private Cliente cliente;
   private Tienda tienda;

    public TiendaV(CentroComercialV centro, Cliente cliente, Tienda tienda) {
        this.centro = centro;
        this.cliente = cliente;
        this.tienda = tienda;
        initComponents();
        this.setLocationRelativeTo(null);
        tienda.entrar(this.cliente);
        ModificarTitulo();
        LlenarLista();
        LlenarPaquetes();
    }

    //Cambia el Titulo del Frame dependiendo de la tienda
   public void ModificarTitulo(){
   this.TiendaLBL.setText(this.tienda.getNombre());
   }
   
       public void LlenarLista() {
        String tabla[][] = new String[tienda.sizeArt()][3];
        Iterator articulosIterator = tienda.getArticulos();
        int i = 0;
        while (articulosIterator.hasNext()) {
            Articulo articulo = (Articulo) articulosIterator.next();
            tabla[i][0] = articulo.getNombre();
            tabla[i][1] = articulo.getID();
            tabla[i][2] = "$" + String.format("%.2f", articulo.getPrecio());
            i++;
        }

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Articulo","ID", "Precio"}
        ));
    }
       
       
         public void LlenarPaquetes() {
        String tabla[][] = new String[tienda.sizePaq()][2];
        Iterator paquetesIterator = tienda.getPaquetes();
        int i = 0;
        while (paquetesIterator.hasNext()) {
            Paquete paquete = (Paquete) paquetesIterator.next();
            tabla[i][0] = paquete.getNombre();
            tabla[i][1] = "$" + String.format("%.2f", paquete.getPrecio());
            i++;
        }

        TablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Paquete", "Precio"}
        ));
    }
       

    
    /**
     * Creates new form Tienda
     */
    public TiendaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TiendaLBL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AñadirArticulo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TiendaLBL.setText("TIENDA");
        jPanel1.add(TiendaLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton1.setText("Añadir al carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        AñadirArticulo.setText("Añadir al carrito");
        AñadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(AñadirArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton3.setText("Quitar del carrito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        jButton4.setText("Quitar del carrito");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel2.setText("Lista de Paquetes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jLabel3.setText("Lista de Articulos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 160, -1));

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaArticulos.setAutoscrolls(false);
        jScrollPane3.setViewportView(TablaArticulos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 220));

        TablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPaquetes.setAutoscrolls(false);
        jScrollPane4.setViewportView(TablaPaquetes);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 370, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        System.out.println(this.cliente.getTienda());
        this.tienda.Salir(cliente);
        System.out.println(this.cliente.getTienda());
        centro.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AñadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirArticuloActionPerformed
        
        int index= this.TablaArticulos.getSelectedRow();
       
        if(index!=-1){
        int counter=0;
        Iterator i = this.tienda.getArticulos();
        
        while(i.hasNext()&&  counter<= index){
        
            Articulo art= (Articulo) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().Añadir(art);
            }
            counter++;
        
        }
        
        }
        
        
    }//GEN-LAST:event_AñadirArticuloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        
       int index= this.TablaArticulos.getSelectedRow();
       
        if(index!=-1){
        int counter=0;
        Iterator i = this.tienda.getArticulos();
        
        while(i.hasNext()&&  counter<= index){
        
            Articulo art= (Articulo) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().Quitar(art);
               
            }
          
            counter++;
        }

        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int index= this.TablaPaquetes.getSelectedRow();
        if(index!=-1){
        int counter=0;
        Iterator i = this.tienda.getPaquetes();
        
        while(i.hasNext()&&  counter<= index){
        
             Paquete paq= (Paquete) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().AñadirPaquete(paq);
         
            }
            counter++;
        
        }
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int index= this.TablaPaquetes.getSelectedRow();
        if(index!=-1){
        int counter=0;
        Iterator i = this.tienda.getPaquetes();
        
        while(i.hasNext()&&  counter<= index){
        
            Paquete paq= (Paquete) i.next();
            
            if(counter==index){
                this.cliente.getCarrito().QuitarPaquete(paq);
   
            }
            counter++;
        
        }
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirArticulo;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTable TablaPaquetes;
    private javax.swing.JLabel TiendaLBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
